routes/admin.php
<?php

Route::get('/', 'PageController@index')->name('dashboard');

Route::delete('entity/{classname}/{id}', 'CrudController@delete')->name('delete-entity');

Route::resource('pages', 'PageController');
Route::prefix('pages')->name('pages.')->group(function() {
    Route::get('create/{menu}', 'PageController@createMenuItem')->name('create.menuitem');
    Route::post('store', 'PageController@storeExtended')->name('store');
    Route::put('update/{page}', 'PageController@updateExtended')->name('update');
    Route::get('static_form_submits/{page}', 'PageController@submittedForms')->name('submits');
});

Route::delete('menuitems/destroy/{menuitem}', 'MenuitemController@destroy')->name('menuitems.destroy');

Route::resource('menus', 'MenuController');
Route::resource('redirects', 'RedirectController');
Route::resource('static_form_submits', 'StaticFormSubmitController')->only(['show']);

Route::resource('mediaitems', 'MediaitemController');
Route::prefix('mediaitems')->group(function() {
    Route::any('ckeditor/upload', 'MediaitemController@uploadCKEditor')->name('ckeditor.upload');
});

Route::name('preview.')
    ->prefix('preview')
    ->group(function() {
        Route::get('page/{page}', 'PageController@preview')->name('pages');
});

Route::name('save-order.')
    ->prefix('save-order')
    ->group(function() {
        Route::post('menuitems', 'MenuitemController@saveOrder')->name('menuitems');
        Route::post('menus', 'MenuController@saveOrder')->name('menus');
});

routes/web.php
<?php

Route::get('/', 'HomeController@show')->name('home');
Route::get('admin', 'Admin\Auth\LoginController@login');

Route::post('contact/{form}', 'ContactController@store')->name('contact.store');

Route::any('{page}', 'PageController@show');

app/Models/Redirect.php
<?php

namespace App\Models;

class Redirect extends BaseModel
{
    /** @var array */
    protected $fillable = [
        'from',
        'to',
    ];

    public static function getFields(): array
    {
        return [
            [
                'name' => 'from',
                'type' => 'text',
                'label' => trans('admin.redirects.fields.from'),
            ],
            [
                'name' => 'to',
                'type' => 'text',
                'label' => trans('admin.redirects.fields.to'),
            ],
        ];
    }
}

app/Http/Controllers/Admin/RedirectController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Admin\CrudController;
use App\Models\Redirect;
use App\Http\Requests\RedirectRequest;

class RedirectController extends CrudController
{
    public function __construct()
    {
        $this->singularModelName = 'redirect';
        $this->pluralModelName = 'redirects';
        $this->modelClass = Redirect::class;
        $this->requestForm = RedirectRequest::class;
    }
}

resources/views/admin/redirect/index.blade.php
@extends('admin.layout')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                @include('admin.form-partials.submit', ['classes' => 'mb-4 d-none sticky-top bg-white'])

                <div class="card">
                    <h2 class="card-header font-weight-bold">
                        {{ trans('admin.redirects.title') }}
                        <a class="btn btn-sm btn-outline-success float-right" href="{{ route('admin.redirects.create') }}"><i class="fas fa-plus"></i> {{ trans('admin.general.add') }}</a>
                    </h2>

                    <ul class="list-group list-group-flush list-group-item-action">
                        @foreach($items as $redirect)
                            <li id="row-{{ $redirect->id }}" class="list-group-item" data-id="{{ $redirect->id }}">
                                <a href="{{ route('admin.redirects.edit', ['redirect' => $redirect]) }}">
                                    {{ $redirect->from }} -> {{ $redirect->to }}
                                </a>

                                <div class="btn-group btn-group-sm float-right" role="group" aria-label="actions">
                                    <button class="btn btn-sm btn-outline-danger js-delete-button" data-id="{{ $redirect->id }}"><i class="fas fa-trash"></i></button>
                                    <a href="{{ route('admin.redirects.edit', ['redirect' => $redirect]) }}" class="btn btn-sm btn-outline-primary"><i class="fas fa-pencil-alt"></i></a>
                                </div>

                                <div class="float-right mr-4 d-none" id="js-delete-container-{{ $redirect->id }}" role="group" aria-label="delete-actions">
                                    <em class="mr-4">{{ trans('admin.general.confirm-delete') }}</em>
                                    <button class="btn btn-sm btn-outline-warning js-delete-confirmed" data-url="{{ route('admin.redirects.destroy', ['redirect' => $redirect]) }}"><i class="fas fa-check"></i></button>
                                    <button class="btn btn-sm btn-outline-primary js-delete-cancelled"><i class="fas fa-times"></i></button>
                                </div>
                            </li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
    </div>

    @include('admin.js.delete-item')
@endsection