routes/admin.php
<?php

Route::get('/', 'PageController@index')->name('dashboard');

Route::delete('entity/{classname}/{id}', 'CrudController@delete')->name('delete-entity');

Route::resource('pages', 'PageController');
Route::prefix('pages')->name('pages.')->group(function() {
    Route::get('create/{menu}', 'PageController@createMenuItem')->name('create.menuitem');
    Route::post('store', 'PageController@storeExtended')->name('store');
    Route::put('update/{page}', 'PageController@updateExtended')->name('update');
    Route::get('static_form_submits/{page}', 'PageController@submittedForms')->name('submits');
});

Route::delete('menuitems/destroy/{menuitem}', 'MenuitemController@destroy')->name('menuitems.destroy');

Route::resource('menus', 'MenuController');
Route::resource('redirects', 'RedirectController');
Route::resource('static_form_submits', 'StaticFormSubmitController')->only(['show']);

Route::resource('mediaitems', 'MediaitemController');
Route::prefix('mediaitems')->group(function() {
    Route::any('ckeditor/upload', 'MediaitemController@uploadCKEditor')->name('ckeditor.upload');
});

Route::name('preview.')
    ->prefix('preview')
    ->group(function() {
        Route::get('page/{page}', 'PageController@preview')->name('pages');
});

Route::name('save-order.')
    ->prefix('save-order')
    ->group(function() {
        Route::post('menuitems', 'MenuitemController@saveOrder')->name('menuitems');
        Route::post('menus', 'MenuController@saveOrder')->name('menus');
});

routes/web.php
<?php

Route::get('/', 'HomeController@show')->name('home');
Route::get('admin', 'Admin\Auth\LoginController@login');

Route::post('contact/{form}', 'ContactController@store')->name('contact.store');

Route::any('{page}', 'PageController@show');

resources/views/admin/create.blade.php
@extends('admin.layout')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card mb-4">
                    <h2 class="card-header font-weight-bold">
                        {{ trans('admin.general.new') }}
                        <a class="btn btn-sm btn-outline-secondary float-right" href="{{ url()->previous() }}"><i class="fas fa-arrow-left"></i> {{ trans('admin.general.back') }}</a>
                    </h2>

                    <div class="card-body">
                        <form action="{{ $action }}" method="POST">
                            @csrf

                            @foreach($model::getFields() as $field)
                                @if (isset($field['role']))
                                    @unlessrole($field['role'])
                                        @continue
                                    @endhasanyrole
                                @endif

                                @includeIf('admin.form-partials.'.$field['type'], [
                                    'name' => $field['name'],
                                    'label' => $field['label'] ?? '',
                                    'options' => $field['options'] ?? [],
                                    'value' => old($field['name']),
                                    'relation' => $field['relation'] ?? [],
                                    'fields' => $field['fields'] ?? [],
                                ])
                            @endforeach

                            @include('admin.form-partials.submit')
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @include('admin.js.ckeditor')
@endsection

resources/views/admin/edit.blade.php
@extends('admin.layout')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card mb-4">
                    <h2 class="card-header font-weight-bold">
                        {{ trans('admin.general.edit') }}
                        <a class="btn btn-sm btn-outline-secondary float-right" href="{{ url()->previous() }}"><i class="fas fa-arrow-left"></i> {{ trans('admin.general.back') }}</a>
                    </h2>

                    <div class="card-body">
                        <form action="{{ $action }}" method="POST">
                            @csrf
                            @method('PUT')

                            @include('admin.form-partials.hidden', [
                                'name' => 'id',
                                'value' => $entity->id,
                            ])

                            @foreach($entity::getFields() as $field)
                                @if (isset($field['role']))
                                    @unlessrole($field['role'])
                                        @continue
                                    @endhasanyrole
                                @endif

                                @includeIf('admin.form-partials.'.$field['type'], [
                                    'name' => $field['name'],
                                    'label' => $field['label'],
                                    'value' => old($field['name']) ?? $entity->{$field['name']},
                                    'options' => $field['options'] ?? [],
                                    'relation' => $field['relation'] ?? [],
                                    'fields' => $field['fields'] ?? [],
                                    'entity' => $entity,
                                ])
                            @endforeach

                            @include('admin.form-partials.submit')
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @include('admin.js.ckeditor')
@endsection

resources/views/admin/layout.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/admin/app.js') }}" defer></script>

    <!-- Styles -->
    <link href="{{ asset('css/admin/app.css') }}" rel="stylesheet">
</head>
<body>
    <div>
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    @auth
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item @if(in_array('menus', request()->segments())) active @endif"><a class="nav-link" href="{{ route('admin.menus.index') }}">{{ trans('admin.menus.title') }}</a></li>
                            <li class="nav-item @if(in_array('pages', request()->segments())) active @endif"><a class="nav-link" href="{{ route('admin.pages.index') }}">{{ trans('admin.pages.title') }}</a></li>
                            <li class="nav-item @if(in_array('redirects', request()->segments())) active @endif"><a class="nav-link" href="{{ route('admin.redirects.index') }}">{{ trans('admin.redirects.title') }}</a></li>
                            <li class="nav-item @if(in_array('mediaitems', request()->segments())) active @endif"><a class="nav-link" href="{{ route('admin.mediaitems.index') }}">{{ trans('admin.mediaitems.title') }}</a></li>
                        </ul>
                    @endauth

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('admin.login') }}">{{ __('Login') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('admin.logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            <div class="container">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            </div>

            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/admin/show.blade.php
@extends('admin.layout')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card mb-4">
                    <h2 class="card-header font-weight-bold">
                        {{ trans('admin.general.show') }}
                        <a class="btn btn-sm btn-outline-secondary float-right" href="{{ url()->previous() }}"><i class="fas fa-arrow-left"></i> {{ trans('admin.general.back') }}</a>
                    </h2>

                    <div class="card-body">
                        @foreach($entity::getFields() as $field)
                            @if (isset($field['role']))
                                @unlessrole($field['role'])
                                    @continue
                                @endhasanyrole
                            @endif

                            @includeIf('admin.show-partials.'.$field['type'], [
                                'name' => $field['name'],
                                'label' => $field['label'],
                                'value' => $entity->{$field['name']},
                                'options' => $field['options'] ?? [],
                                'relation' => $field['relation'] ?? [],
                                'fields' => $field['fields'] ?? [],
                                'entity' => $entity,
                            ])
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>

    @include('admin.js.ckeditor')
@endsection