routes/admin.php
<?php

Route::get('/', 'PageController@index')->name('dashboard');

Route::delete('entity/{classname}/{id}', 'CrudController@delete')->name('delete-entity');

Route::resource('pages', 'PageController');
Route::prefix('pages')->name('pages.')->group(function() {
    Route::get('create/{menu}', 'PageController@createMenuItem')->name('create.menuitem');
    Route::post('store', 'PageController@storeExtended')->name('store');
    Route::put('update/{page}', 'PageController@updateExtended')->name('update');
    Route::get('static_form_submits/{page}', 'PageController@submittedForms')->name('submits');
});

Route::delete('menuitems/destroy/{menuitem}', 'MenuitemController@destroy')->name('menuitems.destroy');

Route::resource('menus', 'MenuController');
Route::resource('redirects', 'RedirectController');
Route::resource('static_form_submits', 'StaticFormSubmitController')->only(['show']);

Route::resource('mediaitems', 'MediaitemController');
Route::prefix('mediaitems')->group(function() {
    Route::any('ckeditor/upload', 'MediaitemController@uploadCKEditor')->name('ckeditor.upload');
});

Route::name('preview.')
    ->prefix('preview')
    ->group(function() {
        Route::get('page/{page}', 'PageController@preview')->name('pages');
});

Route::name('save-order.')
    ->prefix('save-order')
    ->group(function() {
        Route::post('menuitems', 'MenuitemController@saveOrder')->name('menuitems');
        Route::post('menus', 'MenuController@saveOrder')->name('menus');
});

routes/web.php
<?php

Route::get('/', 'HomeController@show')->name('home');
Route::get('admin', 'Admin\Auth\LoginController@login');

Route::post('contact/{form}', 'ContactController@store')->name('contact.store');

Route::any('{page}', 'PageController@show');

app/Models/Menu.php
<?php

namespace App\Models;

use App\Models\Page;
use App\Models\Pivots\Menuitem;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Menu extends BaseModel
{
    /** @var array */
    protected $fillable = [
        'developer_label',
        'title',
        'order',
    ];

    public static function getFields(): array
    {
        return [
            [
                'name' => 'title',
                'type' => 'text',
                'label' => trans('admin.menus.fields.title'),
            ],
            [
                'name' => 'developer_label',
                'type' => 'text',
                'label' => trans('admin.menus.fields.developer_label'),
                'role' => 'super_admin',
            ],
        ];
    }

    public function menuitems(): HasMany
    {
        return $this->hasMany(Menuitem::class)->orderBy('order');
    }

    public function pages(): BelongsToMany
    {
        return $this->belongsToMany(Page::class, 'menuitems', 'menu_id', 'page_id')->using(Menuitem::class);
    }
}

app/Http/Controllers/Admin/MenuController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Admin\CrudController;
use Illuminate\Database\Eloquent\Model;
use App\Models\Menu;
use Illuminate\View\View;
use App\Http\Requests\MenuRequest;

class MenuController extends CrudController
{
    public function __construct()
    {
        $this->singularModelName = 'menu';
        $this->pluralModelName = 'menus';
        $this->modelClass = Menu::class;
        $this->requestForm = MenuRequest::class;
    }

    public function index(): View
    {
        return view('admin.' . $this->singularModelName . '.index')->withItems($this->modelClass::orderBy('order')->get());
    }
}

resources/views/admin/menu/index.blade.php
@extends('admin.layout')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                @include('admin.form-partials.submit', ['classes' => 'mb-4 d-none sticky-top bg-white'])

                <div class="card">
                    <h2 class="card-header font-weight-bold">
                        {{ trans('admin.menus.title') }}
                        <a class="btn btn-sm btn-outline-success float-right" href="{{ route('admin.menus.create') }}"><i class="fas fa-plus"></i> {{ trans('admin.general.add') }}</a>
                    </h2>

                    <ul class="list-group list-group-flush list-group-item-action" id="sortableItems">
                        @foreach($items as $menu)
                            <li id="row-{{ $menu->id }}" class="list-group-item" data-id="{{ $menu->id }}">
                                <a href="{{ route('admin.menus.edit', ['menu' => $menu]) }}">
                                    {{ $menu->title }}
                                </a>

                                <div class="btn-group btn-group-sm float-right" role="group" aria-label="actions">
                                    @if (empty($menu->developer_label))
                                        <button class="btn btn-sm btn-outline-danger js-delete-button" data-id="{{ $menu->id }}"><i class="fas fa-trash"></i></button>
                                    @endif
                                    <a href="{{ route('admin.menus.edit', ['menu' => $menu]) }}" class="btn btn-sm btn-outline-primary"><i class="fas fa-pencil-alt"></i></a>
                                    <button class="btn btn-sm btn-outline-secondary js-order-handle"><i class="fas fa-arrows-alt"></i></button>
                                </div>

                                @if (empty($menu->developer_label))
                                    <div class="float-right mr-4 d-none" id="js-delete-container-{{ $menu->id }}" role="group" aria-label="delete-actions">
                                        <em class="mr-4">{{ trans('admin.general.confirm-delete') }}</em>
                                        <button class="btn btn-sm btn-outline-warning js-delete-confirmed" data-url="{{ route('admin.menus.destroy', ['menu' => $menu]) }}"><i class="fas fa-check"></i></button>
                                        <button class="btn btn-sm btn-outline-primary js-delete-cancelled"><i class="fas fa-times"></i></button>
                                    </div>
                                @endif
                            </li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
    </div>

    @include('admin.js.delete-item')
    @include('admin.js.sorting', [
        'id' => 'sortableItems',
        'xhr_action' => route('admin.save-order.menus'),
    ])
@endsection